// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vddpxkoycgawgdapigvl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZkZHB4a295Y2dhd2dkYXBpZ3ZsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzg4MDM4MzUsImV4cCI6MjA1NDM3OTgzNX0.2hudtSXcnmmLb1d9_I_6H7AWhI9Y_9p8PYkV7sIjgt0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);